### ISSUE TITLE
Netlify deploy issue (resolved), but FYI

### ISSUE THREAD

**Issue by jayroh** [bglw/jekyll-postcss-v2#3]
In your README you mention that you must install postcss and postcss-cli via the following:

`npm i -D postcss postcss-cli`

... which places things in the `devDependencies` hash key in `package.json`. This is fine. Typically running `bundle exec jekyll build` locally will result in everything working just fine. Great!

Here's the hiccup: In many jekyll + postcss blog posts (eg: [here](https://stevenwestmoreland.com/2021/01/using-tailwind-css-with-jekyll.html)) there are instructions that instruct people to set the following ENV variables:

> When building for production, always set `JEKYLL_ENV=production` and `NODE_ENV=production` on the command line. When these variables are set to production, [unused Tailwind styles are purged](https://tailwindcss.com/docs/installation#building-for-production) and the output is processed with [cssnano](https://github.com/cssnano/cssnano).

This where the problem comes in.  `NODE_ENV=production` + `npm i -D` seems to result in an empty `./node_modules` directory.

When I moved everything from `devDependencies` to `dependencies` in `packages.json` then everything started working.

I don't know if this is a Netlify thing or not but, in the off-chance anyone shows up here with missing `node_modules` packages, this might be the answer.

**Comment by bglw** [comment]
Ah, good shout! I have updated the README to make this a normal install so that people don't get caught out for this.

Cheers!
